# Generated by Django 4.1.5 on 2023-01-23 12:13

import django.core.validators
from django.db import migrations, models
import schedule_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0002_alter_person_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='teacher_schedule',
            field=models.FileField(blank=True, upload_to=schedule_app.models.create_user_data_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['json'])]),
        ),
    ]
