# Generated by Django 4.1.5 on 2023-01-23 18:06

from django.db import migrations, models
import schedule_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0003_alter_person_teacher_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='avatar',
            field=models.ImageField(upload_to=schedule_app.models.create_user_data_path, verbose_name='Image'),
        ),
    ]
