# Generated by Django 4.1.5 on 2023-01-26 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0006_alter_person_study_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='study_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule_app.studygroup'),
        ),
    ]
