# Generated by Django 4.1.5 on 2023-01-26 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0010_alter_studyday_day_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyday',
            name='study_format',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='schedule_app.studyformat'),
        ),
    ]
